In [19]:
NAME = "Jun Park"

---

# Lab 6: Skip Gram

**Please read the following instructions very carefully**

## Working on the assignment / FAQs
- **Always use the seed/random_state as *42* wherever applicable** (This is to ensure repeatability in answers, across students and coding environments) 
- The type of question and the points they carry are indicated in each question cell
- To avoid any ambiguity, each question also specifies what *value* must be set. Note that these are dummy values and not the answers
- If an autograded question has multiple answers (due to differences in handling NaNs, zeros etc.), all answers will be considered.
- You can delete the `raise NotImplementedError()`
- **Submitting the assignment** : Download the '.ipynb' file from Colab and upload it to bcourses. Do not delete any outputs from cells before submitting.
- That's about it. Happy coding!


Available software:
 - Python's Gensim module: https://radimrehurek.com/gensim/ (install using pip)
 - Sklearn’s  TSNE module in case you use TSNE to reduce dimension (optional)
 - Python’s Matplotlib (optional)

_Note: The most important hyper parameters of skip-gram/CBOW are vector size and windows size_


In [20]:
!pip install gensim
!wget -nc https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz 


import pandas as pd
import numpy as np 
import gensim
from sklearn.cluster import KMeans

File ‘GoogleNews-vectors-negative300.bin.gz’ already there; not retrieving.



### **Q1 (1 point)** 
Find the cosine similarity between the following word pairs

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)

In [21]:
from gensim.models import KeyedVectors

model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)
word_vectors = model.wv

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  after removing the cwd from sys.path.


In [22]:
#Replace 0 with the code / value; Do not delete this cell
similarity_pair1 = word_vectors.similarity('France','England')
similarity_pair2 = word_vectors.similarity('smaller','bigger')
similarity_pair3 = word_vectors.similarity('England','London')
similarity_pair4 = word_vectors.similarity('France','Rocket')
similarity_pair5 = word_vectors.similarity('big','bigger')


In [23]:
#This is an autograded cell, do not edit/delete
print(similarity_pair1, similarity_pair2, similarity_pair3, similarity_pair4, similarity_pair5)

0.39804944 0.7302272 0.43992856 0.07114174 0.68423855


### **Q2 (1 point)** 
Write an expression to extract the vector representations of the words: 

- France
- England
- smaller
- bigger
- rocket
- big

Get only the first 5 elements for each vector representation.

In [24]:
#Replace 0 with the code / value to get the first 5 elements of each vector; Do not delete this cell
vector_1 = word_vectors['France'][0:5]
vector_2 = word_vectors['England'][0:5]
vector_3 = word_vectors['smaller'][0:5]
vector_4 = word_vectors['bigger'][0:5]
vector_5 = word_vectors['rocket'][0:5]
vector_6 = word_vectors['big'][0:5]



In [25]:
#This is an autograded cell, do not edit/delete
print(vector_1)
print(vector_2)
print(vector_3)
print(vector_4)
print(vector_5)
print(vector_6)


[0.04858398 0.07861328 0.32421875 0.03491211 0.07714844]
[-0.19824219  0.11523438  0.0625     -0.05834961  0.2265625 ]
[-0.05004883  0.03417969 -0.0703125   0.17578125  0.00689697]
[-0.06542969 -0.09521484 -0.06225586  0.16210938  0.01989746]
[-0.03198242  0.27148438 -0.2890625  -0.15429688  0.16894531]
[ 0.11132812  0.10595703 -0.07373047  0.18847656  0.07666016]


### **Q3 (1 point)** 
Find the euclidean distances between the word pairs : 

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)


In [26]:
#Replace 0 with the code / value; Do not delete this cell
eu_dist1 = np.sqrt(np.sum(np.square(word_vectors['France'] - word_vectors['England'])))
eu_dist2 = np.sqrt(np.sum(np.square(word_vectors['smaller'] - word_vectors['bigger'])))
eu_dist3 = np.sqrt(np.sum(np.square(word_vectors['England'] - word_vectors['London'])))
eu_dist4 = np.sqrt(np.sum(np.square(word_vectors['France'] - word_vectors['Rocket'])))
eu_dist5 = np.sqrt(np.sum(np.square(word_vectors['big'] - word_vectors['bigger'])))



In [27]:
#This is an autograded cell, do not edit / delete
print(eu_dist1)
print(eu_dist2)
print(eu_dist3)
print(eu_dist4)
print(eu_dist5)


3.0151067
1.8618743
2.8752837
3.892071
1.9586496


### **Q4 (1 point)**
Time to dabble with the power of Word2Vec. Find the 2 closest words  for the following conditions:  
- (King - Man + Queen)
- (bigger - big + small)
- (waiting - wait + run)
- (Texas + Milwaukee – Wisconsin)

In [28]:
#Replace 0 with the code / value; Do not delete this cell
closest1 = word_vectors.most_similar(positive=['King', 'Queen'], negative=['Man'])[0:2]
closest2 = word_vectors.most_similar(positive=['bigger', 'small'], negative=['big'])[0:2]
closest3 = word_vectors.most_similar(positive=['waiting', 'run'], negative=['wait'])[0:2]
closest4 = word_vectors.most_similar(positive=['Texas', 'Milwaukee'], negative=['Wisconsin'])[0:2]
closest5 = 0






In [29]:
#This is an autograded cell, do not edit/delete
print(closest1)
print(closest2)
print(closest3)
print(closest4)
print(closest5)


[('Queen_Elizabeth', 0.5257916450500488), ('monarch', 0.5004087090492249)]
[('larger', 0.7402471899986267), ('smaller', 0.732999324798584)]
[('running', 0.5654535889625549), ('runs', 0.49640005826950073)]
[('Houston', 0.7767744064331055), ('Fort_Worth', 0.7270511388778687)]
0


### **Q5 (3 points)**
Using the vectors for the words in the Google News dataset, explore the semantic representation of these words through K-means clustering and explain your findings.

*Note : Since there are ~3Mil words in the vocabulary, you can downsample it to ~20-30k randomly selected words*

**Do not delete the below cell**

In [64]:
random_words = np.random.choice(word_vectors.index2word, size = 20000, replace = False)
word_vectors = word_vectors[random_words]
k_means = KMeans(n_clusters = 10, random_state = 42)
k_means.fit(word_vectors)
labels = k_means.labels_
data = {'word': random_words, 'cluster': labels}
df = pd.DataFrame(data)

In [65]:
words_by_cluster = df.groupby('cluster').agg(lambda x: list(x))
words_by_cluster

word
cluster                                                   
0        [support_GNET, Mothering_Magazine, Extends_Dea...
1        [Lorcan_Cranitch, Sidney_Blumenthal, Trey_Anas...
2        [Norjan, Syed_Zahid_Hussain, Rehmani, Kamal_Ja...
3        [Honeywill, Matic, Sherlock, Duimstra, Louer, ...
4        [Bisk_Education, Sport_Chek, Earthwatch_Instit...
5        [SilverCity_Riverport_Cinemas, IS_CURRENTLY, P...
6        [Belvo, Penarth_Vale, Erpingham, asthma_suffer...
7        [Wal_i_Musi, Jiangxi_Copper_Ltd., Ricardo_Teix...
8        [Image_Signal_Processor, SJ##, PCIe_x1_slots, ...
9        [Fang_Wei, distinctively_flavored, Mike_Van_So...

In [78]:
## Cluster 0
np.array(words_by_cluster.iloc[0,:])
print('Cluster 0 represents words relating to the news media industry. \nThere are journalists, newspaper titles, etc. in this cluster.')

Cluster 0 represents words relating to the news media industry. 
There are journalists, newspaper titles, etc. in this cluster.


In [77]:
## Cluster 1
np.array(words_by_cluster.iloc[1,:])
print('Cluster 1 represents words relating to the entertainment industry. \nThere are songwriters, actors, etc. in this cluster.')

Cluster 1 represents words relating to the entertainment industry. 
There are songwriters, actors, etc. in this cluster.


In [76]:
## Cluster 2
np.array(words_by_cluster.iloc[2,:])
print('Cluster 2 represents words relating to education and government. \nThere are names of teachers, scientists, doctors, government officials, etc. in this cluster.')

Cluster 2 represents words relating to education and government. 
There are names of teachers, scientists, doctors, government officials, etc. in this cluster.


In [83]:
## Generalized
print('I found that each of the clusters contained words related to a certain topic. \nAlthough I only went through the first three clusters, I could see that the \nmajority of the words related to a certain topic that could be generalized \nto all of the words in that cluster.')

I found that each of the clusters contained words related to a certain topic. 
Although I only went through the first three clusters, I could see that the 
majority of the words related to a certain topic that could be generalized 
to all of the words in that cluster.


### **Q6 (1 point)**
What loss function does the skipgram model use and briefly describe what this function is minimizing.

**Do not delete the below cell**

In [33]:
# The skipgram model uses categorical cross entropy loss with a softmax activation.
# Categorical cross entropy loss as a loss function minimizes
# the negative log likelihood of the data belonging to its class summed up
# for all classes in the model.


### **Bonus Question (1 point)** 
Find at least 2 interesting word vec combinations like the ones given in Q4

**Do not delete the below cell**

In [34]:
# Bugatti - sportscar + SUV
# If you subtract the sportscar aspect from Bugatti, a high-end sportscar company, you are left with a high-end car company
# If you add SUV to that, you would expect to see luxury SUV models, which was correct
# The Cadillax Escalade and Ford Expedition are both high-end SUVs in the automotive industry
print(word_vectors.most_similar(positive=['Bugatti', 'SUV'], negative=['sportscar'])[0:2])

# NBA - basketball + soccer
# If you subtract basketball from NBA, a basketball league, you are left with a sports league
# If you add soccer to that, you would expect to see examples of soccer leagues, which was correct
# The MLS is a soccer league and FIFA is representative of the soccer association
print(word_vectors.most_similar(positive=['NBA', 'soccer'], negative=['basketball'])[0:2])

[('Cadillac_Escalade', 0.5963462591171265), ('Ford_Expedition', 0.5706534385681152)]
[('MLS', 0.640450119972229), ('FIFA', 0.5651741623878479)]
